# ***************************************************************
#
#  Copyright (C) 2026, Pelican Project, Morgridge Institute for Research
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you
#  may not use this file except in compliance with the License.  You may
#  obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# ***************************************************************

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        # Allow files such as docs/parameters.yaml.
        args: [--allow-multiple-documents]
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  #
  # Check semantics.
  #
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.9.0
    hooks:
      - id: golangci-lint
        # This can be one of the more time-consuming checks.
        stages: [pre-push, manual]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        # Require that only the most serious problems be addressed.
        args: [--severity=warning]
  #
  # Standardize formatting.
  #
  - repo: local
    hooks:
      - id: npm-format-fix
        name: reformat web frontend code
        language: system
        entry: bash -c "cd web_ui/frontend && npm run format:fix"
        pass_filenames: false
        files: web_ui/frontend/.*
        # Web developer's personal preference.
        stages: [pre-push, manual]
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-simple-breaks
        args: [--wrap, "no"]
        files: \.md$
  - repo: https://github.com/crate-ci/typos
    rev: v1.43.4
    hooks:
      - id: typos
        # Prevent false positives from mangling files.
        # The hook's default behavior is to fix alleged typos.
        args: [--sort, --force-exclude]
