# Configure 'typos' to reduce false positives.
# For more information, see <https://github.com/crate-ci/typos>.

[default]
extend-ignore-identifiers-re = [
    ## Ignore TLAs. Two and three letter acronyms are not worth fixing.
    "^[A-Za-z]{2,3}$",
    ## Ignore lotman's use of 'ded' for 'dedicated'.
    "^ded[A-Z]",
    "^[a-z]+Ded",
    ## Ignore server_utils's use of 'dne' for 'does not exist'.
    "_dne$",
]

[default.extend-identifiers]
## The 'cipher' library uses "Encrypter"; 'typos' prefers "Encryptor".
NewCFBEncrypter = "NewCFBEncrypter"
## HTCondor's daemon names follow the usual "{word} + 'd'" convention.
StartdAttrs = "StartdAttrs"
condor_startd = "condor_startd"

[files]
extend-exclude = [
    ## Ignore configuration files and the like.
    "go.mod",
    "xrootd/resources/osdf-authfile",
    ## Ignore this script because of its inline certificates.
    "github_scripts/osx_install.sh",
]
