# Origin export configuration to test broker functionality

Director:
  EnableBroker: true

Origin:
  SelfTest: False
  DirectorTest: False

  StorageType: "posix"
  EnableBroker: true
  EnableDirectReads: true
  Exports:
    - StoragePrefix: /<SHOULD BE OVERRIDDEN>
      FederationPrefix: /test
      Capabilities: ["PublicReads", "Writes", "DirectReads", "Listings"]

Cache:
  SelfTest: False
  DirectorTest: False
