---
name: Check Go Generate Has Been Run

on:
  push:
    branches:
      - "main"
      - "v[0-9]+.[0-9]+.*"
  pull_request:
  workflow_dispatch:

jobs:
  check-go-generate:
    name: Check Go Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Run Go Generate
        run: go generate ./...

      - name: Validate that generated files are up to date
        run: |
          if git diff --quiet; then
            echo "No changes found."
          else
            echo "Changes detected. Here are the details:"
            git diff
            exit 1
          fi
