name: Check Go Generate Has been Run
on:
  pull_request:
jobs:
  validate-generated-files:
    name: Check Go Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run Go Generate
        run: go generate ./...

      - name: Validate Generated Files are up to date
        run: |
          if git diff --quiet; then
            echo "No changes found."
          else
            echo "Changes detected. Here are the details:"
            git diff
            exit 1
          fi
